---
name: CI - Cron

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:

  pre-commit:
    name: Call Pre-Commit run
    uses: mighty-muffin/.github/.github/workflows/reusable-pre-commit.yml@main

  secret:
    needs:
      - pre-commit
    name: Call Secret Scanning
    uses: mighty-muffin/.github/.github/workflows/reusable-gitguardian.yml@main

    secrets:
      GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

  renovate:
    name: Call Renovate Dependency Update
    uses: mighty-muffin/.github/.github/workflows/reusable-renovate.yml@main
