---
name: Reusable - Prek

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      configuration_file:
        description: Prek configuration
        required: false
        default: ""
        type: string
      skips:
        description: Prek Skip
        required: false
        default: ""
        type: string


jobs:
  Prek:
    name: Run Prek
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Run Pre-Commit Checks
        uses: j178/prek-action@91fd7d7cf70ae1dee9f4f44e7dfa5d1073fe6623 # v1.0.11
        env:
          SKIP: ${{ inputs.configuration_file }}
        with:
          extra_args: ${{ inputs.configuration_file }}
