---
name: Reusable - Release Tag
on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      changelog_file:
        description: "Path to the changelog file"
        required: true
        default: "CHANGELOG.md"
        type: string

jobs:
  release-tag:
    name: Run release tag
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: 3.14

      - name: Get version from tag
        id: tag_name
        run: |
          echo ::set-output name=current_version::${GITHUB_REF#refs/tags/v}
        shell: bash

      - name: Get notes
        id: generate_notes
        uses: anmarkoulis/commitizen-changelog-reader@0692c1865c3ccf530ddfc8d0870f4d1ab559b767 # master
        with:
          tag_name: ${{ github.ref }}
          changelog: ${{ inputs.changelog_file }}

      - name: Create Release Notes File
        run: |
          echo "${{join(fromJson(steps.generate_notes.outputs.notes).notes, '')}}" > ${{ github.workspace }}-GH_CHANGELOG.md

      - name: GH Release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2
        if: github.ref_type == 'tag'
        with:
          body_path: ${{ github.workspace }}-GH_CHANGELOG.md
          repository: ${{ github.repository }}
          token: ${{ secrets.RELEASE_PAT }}
